### ISSUE TITLE
Slice für ICD-O-3

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-diagnose#11]
Slice für ICD-O-3 hinzufügen - Anfrage aus Modul Biobank

**Comment by julsas** [comment]
- [ ] Extension Diagnosesicherheit + ValueSet
- [ ] CodeSystem ICD-O-3
- [ ] ValueSets Morphologie / Topographie

**Comment by julsas** [comment]
bf58551baacd3232c2c0edd51819849d91edc324

Wurde aus diesem Modul entfernt. Das Thema ICD-O-3 soll komplett im Modul Onkologie definiert werden.
