### ISSUE TITLE
Fehlende Codes in ICD-10 CodeSystem

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-diagnose#3]
CodeSystem ist zur Zeit nicht 'complete', weil der Claml Konverter gerade noch keine Modifier unterstützt.

**Comment by alexzautke** [comment]
Siehe https://chat.fhir.org/#narrow/stream/179307-german.2Fmi-initiative/topic/.5BDiagnose.5D.20ICD-10-Codes.20nicht.20im.20ValueSet.20enthalten
