### ISSUE TITLE
[HDB-233] Mehrfachkodierungs-Kennzeichen in Extension oder code.coding.code

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-diagnose#35]
Im Condition-Profil gibt es eine neue Extension für das Kennzeichen einer Mehrfachkodierung eines ICD-Kodes (z.B: !). Anhand der Beschreibung im IG ist nicht klar, ob das Kennzeichen nur bei der Extension aufgeführt werden soll und bei dem tatsächlichen Kode in code.coding.code abgeschnitten werden muss (z.B. ! bei Extension und U07.0 bei code.coding.code) oder ob das Kennzeichen bei der Extension und bei code.coding.code stehen soll (z.B. ! bei Extension und U07.0! bei code.coding.code). Eine genauere Erläuterung im IG wäre hilfreich.

**Comment by jpwiedekopf** [comment]
Could the extension also be added to the profile in the slice with cardinality 0..* to make clear that it should be used here if appropriate?

**Comment by julsas** [comment]
> Could the extension also be added to the profile in the slice with cardinality 0..* to make clear that it should be used here if appropriate?

Not sure I understand correctly, but the extension should only exist inside the icd10-gm-Slice

**Comment by jpwiedekopf** [comment]
Hi, I think my question was about the extension not being visible in the profile, but I just saw that the extension is provided in `Condition.code.coding:icd10-gm.extension:Mehrfachcodierungs-Kennzeichen` within the [profile](https://simplifier.net/mii-basismodul-diagnose-2024/mii_pr_diagnose_condition). I think I only checked the diff, not the snapshot, so I must have missed the extension.

Regardless, the use of the extension should be clarified in the IG, so the issue has to stay open for now!

**Comment by julsas** [comment]
> Hi, I think my question was about the extension not being visible in the profile, but I just saw that the extension is provided in `Condition.code.coding:icd10-gm.extension:Mehrfachcodierungs-Kennzeichen` within the [profile](https://simplifier.net/mii-basismodul-diagnose-2024/mii_pr_diagnose_condition). I think I only checked the diff, not the snapshot, so I must have missed the extension.
> 
> Regardless, the use of the extension should be clarified in the IG, so the issue has to stay open for now!

Added some explanation here: 38caa8f

**Comment by jpwiedekopf** [comment]
LGTM!
