### ISSUE TITLE
CodeSystem Alpha-ID is missing

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-diagnose#36]
The CodeSystem for Alpha-ID is missing. I talked to Josef Schepers about this during the last AG IOP, and he agrees that having a straight-up conversion of the CSV file the BfArM distributes would suffice for our purposes.

**Comment by jpwiedekopf** [comment]
See https://gitlab.com/mii-termserv/fhir-resources/bfarm/de.bfarm.alpha-id-se and the NPM package at https://gitlab.com/mii-termserv/fhir-resources/bfarm/de.bfarm.alpha-id-se/-/packages. The SU-TermServ server will provide this package for Alpha-ID - a VS can now be defined.

**Comment by julsas** [comment]
Alpha-ID binding jetzt vorhanden
