### ISSUE TITLE
Missing bindings in Condition profile

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-diagnose#38]
There are missing bindings for Alpha-ID, ICD-O-3, OrphaNet in `Condition.code`, and `Condition.bodySite` for SNOMED CT and ICD-O-3.

For `Condition.code`, Alpha-ID and OrphaNet are not available yet (#36, #37), but there should still be a ValueSet and binding (since all codes are allowed, the VS can be easily created in advance of the CodeSystem).

For `Condition.bodySite`, there should be bindings for a VS similar to ECL `<< 123037004 |Body structure (body structure)|` for SNOMED CT, and ICD-O-3 might be doable using a regex VS most easily.

**Comment by geloro94** [comment]
Untl this is fixed, we cannot add the codings to the search ontology of the FDPG.

**Comment by jpwiedekopf** [comment]
CS are now available (see linked issues #36, #37). Both packages defines URLs for implicit VS -> bindings can now be created, if desired, a VS could also be added to the CDS package.

**Comment by ThomasDeBe** [comment]
@julsas Seems to be available, could we do a minor release in the upcoming months?

**Comment by julsas** [comment]
- Alpha-ID und OrphaNet haben jetzt required bindings
- ICD-O-3 entfernt. Jetzt im Modul Onkologie
- `Condition.bodySite` SNOMED slice hat required binding
