### ISSUE TITLE
CodeSystem Kollision

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-diagnose#7]
Betrifft Datenelement '[Resistenz (EUCAST)'](https://art-decor.org/ad/#/mide-/datasets/dataset/2.16.840.1.113883.3.1937.777.24.1.1/2018-06-05T12:44:12/concept/2.16.840.1.113883.3.1937.777.24.2.2494/2022-02-16T15:32:14) 
bzw. das dort Verwendete ValueSet '[Resistenz-EUCAST](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.110/2022-07-15T12:51:58)' bzw. konkret das hier verwendete CodeSystem '[EUCAST](https://art-decor.org/ad/#/mide-/terminology/codesystems/2.16.840.1.113883.3.1937.777.24.5.1/2022-12-02T14:42:20)'

Die OID dieses CodeSystems wurde bereits von einem CodeSystem des Erw.moduls Consent verwendet, allerdings zu einer Zeit, wo ART-DECOR das noch nicht unterstützt hat.

Dieses CodeSystem wird im ValueSet '[MI-I Einwilligung Frage 1b](https://art-decor.org/ad/#/mide-/terminology/valueset/2.16.840.1.113883.3.1937.777.24.11.8/2020-01-14T18:48:09)', dass mittlerweile nicht mehr in Verwendung ist. Es wird allerdings noch immer referenziert

Vorschlag: Die OID sollte auf eine freie und nicht verwendete OID geändert werden, z.B. 2.16.840.1.113883.3.1937.777.24.5.4

**Comment by julsas** [comment]
@SebStaeubert das Issue betrifft das Modul Mikrobiologie und nicht Diagnose, oder?

**Comment by SebStaeubert** [comment]
Aus Sicht der MII BC Value Sets besteht m.E. kein akuter Handlungsbedarf, da die aktuell verwendeten CodeSystem OIDs korrigiert wurden.
Aus Sicht des EUCAST CodeSystems werden nat. noch "Benutzungen" angezeigt, die aufgrund der Kollision auf veraltete Consent Objekte zeigen: https://art-decor.org/ad/#/mide-/terminology/codesystems/2.16.840.1.113883.3.1937.777.24.5.1/2022-12-02T14:42:20
Das kann vermutlich nur von ART-DECOR Admins korrigiert werden.
